### ISSUE TITLE
clone site

### ISSUE THREAD

**Issue by Butonix** [luojxxx/Social-Network#1]
Hello Friend!
I saw your work, is cool!
I wanted to ask you, can you make a clone of this site https://tjournal.ru ?
I'm ready to pay you
I do not hurry, you can do as a hobby in your spare time.

**Comment by amiller911** [comment]
> Hello Friend!
> I saw your work, is cool!
> I wanted to ask you, can you make a clone of this site https://tjournal.ru ?
> I'm ready to pay you
> I do not hurry, you can do as a hobby in your spare time.

Hello.

I have source code tjournal.ru

You want it? If want, so send me mail please a.miller.idd@gmail.com

Thank you.

**Comment by Butonix** [comment]
> > Hello Friend!
> > I saw your work, is cool!
> > I wanted to ask you, can you make a clone of this site https://tjournal.ru ?
> > I'm ready to pay you
> > I do not hurry, you can do as a hobby in your spare time.
> 
> Hello.
> 
> I have source code tjournal.ru
> 
> You want it? If want, so send me mail please [a.miller.idd@gmail.com](mailto:a.miller.idd@gmail.com)
> 
> Thank you.

What programming language is it written in? Got a demo?

**Comment by amiller911** [comment]
> > > Hello Friend!
> > > I saw your work, is cool!
> > > I wanted to ask you, can you make a clone of this site https://tjournal.ru ?
> > > I'm ready to pay you
> > > I do not hurry, you can do as a hobby in your spare time.
> > 
> > 
> > Hello.
> > I have source code tjournal.ru
> > You want it? If want, so send me mail please [a.miller.idd@gmail.com](mailto:a.miller.idd@gmail.com)
> > Thank you.
> 
> What programming language is it written in? Got a demo?

Have 2 select.

1) I have full **original** frontend from tjournal.ru. Use js language, but dont have backend. But can write it if you need.
2) I have project how tjournal.ru. Use vue, laravel. But still have little bugs. If you interesting it i can give you link for see demo.

Thank you.

**Comment by Butonix** [comment]
> > > > Hello Friend!
> > > > I saw your work, is cool!
> > > > I wanted to ask you, can you make a clone of this site https://tjournal.ru ?
> > > > I'm ready to pay you
> > > > I do not hurry, you can do as a hobby in your spare time.
> > > 
> > > 
> > > Hello.
> > > I have source code tjournal.ru
> > > You want it? If want, so send me mail please [a.miller.idd@gmail.com](mailto:a.miller.idd@gmail.com)
> > > Thank you.
> > 
> > 
> > What programming language is it written in? Got a demo?
> 
> Have 2 select.
> 
> 1. I have full **original** frontend from tjournal.ru. Use js language, but dont have backend. But can write it if you need.
> 2. I have project how tjournal.ru. Use vue, laravel. But still have little bugs. If you interesting it i can give you link for see demo.
> 
> Thank you.

Yes. Send me demo please
